name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Get Version and ENV from .envars
      run: |
        source .envars
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ENV=$ENV" >> $GITHUB_ENV
        echo "PREV=$PREV" >> $GITHUB_ENV
        echo "LATEST=$LATEST" >> $GITHUB_ENV

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_HUB }}

    - name: Delete Old Images
      uses: bots-house/docker-hub-delete-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
        repository: statusquonjc46/ssh-portfolio
        tags: ${{ env.PREV }}, ${{ env.LATEST }}

    - name: Delete old images
      run: |
        # Get authentication token
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
        -d '{"username": "${{ secrets.DOCKER_USER }}", "password": "${{ secrets.DOCKER_HUB }}"}' \
        https://hub.docker.com/v2/users/login/ | jq -r .token)
    
        # Delete specific tag
        curl -X DELETE \
        -H "Authorization: JWT ${TOKEN}" \
        https://hub.docker.com/v2/repositories/statusquox27/ssh-portfolio/tags/old-tag/
